# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = u'CepGen'
copyright = u'2013-@CURRENT_YEAR@, the CepGen Collaboration'
author = u'Laurent Forthomme'

# The short X.Y version
version = u'@CEPGEN_VERSION@'
# The full version, including alpha/beta/rc tags
release = u'@CEPGEN_VERSION@'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'myst_parser',
    'sphinx_git',
    #'sphinx_github_changelog',
    #'sphinxcontrib.bibtex',
    #'sphinxcontrib.doxylink',
    'sphinx_togglebutton',
    'sphinx_toolbox.collapse',
    'sphinx_math_dollar',
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
]

bibtex_bibfiles = ['@CMAKE_CURRENT_SOURCE_DIR@/_static/bibliography.bib']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['@CMAKE_CURRENT_SOURCE_DIR@/_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown'
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'_build',
                    'README.md', 'CMakeLists.txt', 'requirements.txt', 'build', 'doxygen-awesome-css',
                    'Doxygen_index.md',
                    'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'colorful'
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_logo = '@CMAKE_CURRENT_SOURCE_DIR@/_static/small-cepgen-logo.png'

#import pietroalbini_sphinx_themes
#html_theme_path = [pietroalbini_sphinx_themes.themes_path()]
#html_theme = "pietroalbini"

#import sphinx_redactor_theme
#html_theme = 'sphinx_redactor_theme'
#html_theme_path = [sphinx_redactor_theme.get_html_theme_path()]

#html_theme = 'sphinx_rtd_theme'
#html_theme = 'alabaster'
#html_theme = 'karma_sphinx_theme'
#html_theme = 'furo'
#html_theme = 'piccolo_theme'
html_theme = 'sphinx_book_theme'

html_extra_path = ['@CMAKE_CURRENT_SOURCE_DIR@/.htaccess']

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'repository_url': 'https://github.com/cepgen/cepgen',
    'repository_branch': 'master',
    'use_download_button': False,
    'use_fullscreen_button': False,
    'use_issues_button': False,
    'use_repository_button': True,
    'path_to_docs': 'docs/',
}
html_use_index = True

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['@CMAKE_CURRENT_SOURCE_DIR@/_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'CepGendoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': r'',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'CepGen.tex', u'CepGen Documentation',
     u'Laurent Forthomme', 'manual'),
]

mathjax3_config = {
  'tex': {
    'inlineMath': [["\\(","\\)"]],
    'displayMath': [["\\[","\\]"]],
    'processEscapes': True,
    'macros': {
      'Pom': "{\\rm I\\!P}",
      'Reg': "{\\rm I\\!R}",
      'gg': ["{\\gamma\\gamma\\rightarrow #1}", 1],
      'ggx': "{\\gg{X}}",
      'ggll': "{\\gg{\\ell^+\\ell^-}}",
      'ggff': "{\\gg{f\\bar f}}",
      'ggww': "{\\gg{W^+W^-}}",
      'kt': "{k_{\\rm T}}",
      'pt': "{p_{\\rm T}}",
      'vecqt': "{\\bf q_{\\rm T}}",
      'xbj': "{x_{\\rm Bj}}",
    }
  },
}


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'cepgen', u'CepGen Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'CepGen', u'CepGen Documentation',
     author, 'CepGen', 'A central exclusive processes event generator.',
     'Miscellaneous'),
]

# Substitution
'''def ultimateReplace(app, docname, source):
    res = source[0]
    for key in app.config.ultimate_replacements:
        res = res.replace(key, app.config.ultimate_replacements[key])
    source[0] = res

from os import path
ultimate_replacements = {
    "{CEPGEN_PATH}" : path.relpath('@CEPGEN_PATH@', path.dirname(__file__))+'/',
}'''

# Breathe Configuration
breathe_default_project = "CepGen"
breathe_implementation_filename_extensions = ['.cxx', 'cc', '.C', '.f']

doxylink = {
    'cepgen': ('@CMAKE_CURRENT_SOURCE_DIR@/cepgen.tag', '/docs/'),
}

# Changelog configuration
sphinx_github_changelog_token = '@GH_API_TOKEN@'

def setup(app):
    app.add_css_file('hacks.css')
    app.add_config_value('ultimate_replacements', {}, True)
    #app.connect('source-read', ultimateReplace)
