name: Documentation
on:
  push:
env:
  CEPGEN_PATH: /Package

jobs:
  cepgen:
    uses: cepgen/cepgen/.github/workflows/build.yml@master
  doc:
    needs: cepgen
    runs-on: ubuntu-latest
    container:
      image: 'laufor/ci-images:cepgen-fedora39'
      options: -v ${{ github.workspace }}:/Documentation
    steps:
    - name: 'Python requirements'
      run: |
        sudo pip install -r requirements.txt

    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: 'Install SSH Key'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: 'Add known hosts'
      run: mkdir -p ~/.ssh && ssh-keyscan -p 222 -H login.hepforge.org >> ~/.ssh/known_hosts

    - name: 'CepGen fetch'
      uses: actions/download-artifact@v4
      with:
        name: build-env
    - name: 'CepGen uncompress'
      run: |
        tar -xvf environment.tar -C /

    - name: 'Configure the build'
      run: |
        cmake -GNinja -B /Documentation/build -DGH_API_TOKEN=${{ secrets.GH_API_TOKEN }}

    - name: 'Generate cepgen documentation'
      working-directory: /Documentation/build
      run: |
        ${{ env.CEPGEN_PATH }}/build/bin/cepgenDocGenerator -o /Documentation/doc/.raw_modules.html -e
        cmake --build /Documentation/build -- Sphinx
    #- name: 'Upload documentation'
    #  uses: burnett01/rsync-deployments@5.2.1
    #  with:
    #    switches: -arvz --no-perms --no-owner --no-group --delete -O -q
    #    path: build/doc/output_html/
    #    remote_path: ~/cepgen/public_html/
    #    remote_host: login.hepforge.org
    #    remote_port: 222
    #    remote_user: ${{ secrets.SSH_USER }}
    #    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
