name: Documentation
on:
  push:
  workflow_dispatch:
env:
  CEPGEN_PATH: /Package

jobs:
  doc:
    runs-on: ubuntu-latest
    container:
      image: 'laufor/ci-images:cepgen-fedora39'
      options: -v ${{ github.workspace }}:/Documentation
    steps:
    - uses: actions/checkout@v4
    - name: 'Python requirements'
      run: |
        sudo pip install -r requirements.txt

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: 'Install SSH Key'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: 'Add known hosts'
      run: mkdir -p ~/.ssh && ssh-keyscan -p 222 -H login.hepforge.org >> ~/.ssh/known_hosts

    - name: 'Download CepGen artifact'
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: build-env
        repo: cepgen/cepgen

    - name: 'CepGen uncompress'
      run: |
        tar -xvf environment.tar -C /

    - name: 'Configure the build'
      run: |
        git config --global --add safe.directory ${{ github.workspace }}
        git submodule update --init
        cmake -GNinja -B /Documentation/build -DGH_API_TOKEN=${{ secrets.GH_API_TOKEN }}

    - name: 'Generate cepgen documentation'
      working-directory: /Documentation/build
      run: |
        ${{ env.CEPGEN_PATH }}/build/bin/cepgenDocGenerator -o /Documentation/.raw_modules.html -e
        cmake --build /Documentation/build

    - name: 'Upload Sphinx website'
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -arvz --no-perms --no-owner --no-group --delete -O -q
        path: build/output_html/
        remote_path: ~/cepgen/public_html/
        remote_host: login.hepforge.org
        remote_port: 222
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 'Upload Doxygen documentation'
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -arvz --no-perms --no-owner --no-group --delete -O -q
        path: build/doxygen/html/
        remote_path: ~/cepgen/public_html/docs/
        remote_host: login.hepforge.org
        remote_port: 222
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
