name: Documentation
on:
  push:
  workflow_dispatch:
env:
  CEPGEN_PATH: /Package

jobs:
  doc:
    runs-on: ubuntu-latest
    container:
      image: 'laufor/ci-images:cepgen-fedora39'
      options: -v ${{ github.workspace }}:/Documentation
    steps:
    - uses: actions/checkout@v4
    - name: 'Python requirements'
      run: |
        sudo pip install -r requirements.txt

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: 'Install SSH Key'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: 'Add known hosts'
      run: mkdir -p ~/.ssh && ssh-keyscan -p 222 -H login.hepforge.org >> ~/.ssh/known_hosts

    - name: 'Download CepGen artifact'
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: build-env
        repo: cepgen/cepgen

    - name: 'Download CepGen benchmarking artifacts'
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: benchmark-env
        repo: cepgen/cepgen

    - name: 'Download CepGen validation artifacts'
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: validation-env
        repo: cepgen/cepgen

    - name: 'CepGen uncompress'
      run: |
        tar -xvf environment.tar -C /
        tar -xvf benchmark-environment.tar -C /Documentation/_static/ Package --strip-components=1
        tar -xvf validation-environment.tar -C /Documentation/_static/ Package/validation --strip-components=1

    - name: 'Configure the build'
      run: |
        git config --global --add safe.directory '*'
        git submodule update --init
        cmake -GNinja -B /Documentation/build -DGH_API_TOKEN=${{ secrets.GH_API_TOKEN }}

    - name: 'Generate cepgen documentation'
      working-directory: /Documentation/build
      run: |
        ${{ env.CEPGEN_PATH }}/bin/cepgenDescribeModules -D "ctml<{useBS:on,pageTitle:,showGit:off,bare:on}" -o /Documentation/.raw_modules.html
        cmake --build /Documentation/build

    - name: 'Upload Sphinx/Doxygen website'
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -arv --inplace --no-perms --no-owner --no-group -O
        path: build/output/
        remote_path: ~/cepgen/public_html/
        remote_host: login.hepforge.org
        remote_port: 222
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
